### ISSUE TITLE
Don't disable the Expose Function button when k8s Service exists

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#1961] opened 2020-09-04 06:25 UTC
**Description**

As in title.

In Function view, we disable the `Expose Function` button when Function is building and deploying, even if user change the Function's code/deps. We should change the behaviour -> disable only when k8s Service doesn't exist (creation step), not when Function's status is different than `Ready`.

**Comment by VishnAndr** [comment] 2021-03-12 07:17
The issue is still there in 1.19

**Comment by VishnAndr** [comment] 2021-05-14 22:44
Not stale. We're waiting still. The issue is still there in 1.20

**Comment by kwiatekus** [comment] 2021-09-30 07:17
console will be discontinued in favor of busoal. Closing...

**Closed** 2021-09-30 07:16 UTC
Labels: bug, wontfix, area/console, area/serverless
