### ISSUE TITLE
Catalog UI context not initialised on time

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1791] opened 2020-05-14 10:21 UTC
**Description**

It happens that catalog ui crashes with undefined reference error.

**Attachment**

![Screen Shot 2020-05-14 at 12 16 28](https://user-images.githubusercontent.com/6783567/81922999-45d32d00-95dd-11ea-92d2-90ac45c351fa.png)

```
react-dom.production.min.js:196 TypeError: Cannot read property 'includes' of undefined
    at Ce (helpers.js:59)
    at Ia (App.js:25)
    at ho (react-dom.production.min.js:154)
    at Ts (react-dom.production.min.js:259)
    at Au (react-dom.production.min.js:230)
    at Du (react-dom.production.min.js:229)
    at wu (react-dom.production.min.js:223)
    at yu (react-dom.production.min.js:214)
    at il (react-dom.production.min.js:279)
    at react-dom.production.min.js:282
```

**Steps to reproduce**

It happens rarely and quite randomly

**Comment by sjanota** [comment] 2020-05-18 10:14
Happens also on add-ons 
<img width="1147" alt="Screen Shot 2020-05-18 at 12 13 31" src="https://user-images.githubusercontent.com/5119235/82201744-1d12a680-9901-11ea-98bd-d6dc1091b10d.png">

**Comment by Wawrzyn321** [comment] 2020-06-08 12:35
Duplicate of #1792

**Closed by Wawrzyn321** 2020-06-08 12:35 UTC
Labels: area/console, bug
