### ISSUE TITLE
Empty list consistency 

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#683] opened 2019-03-12 12:37 UTC
Apply same styles for empty lists placeholders:

![Screen Shot 2019-03-12 at 13.28.45.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/b0a6b98b-e7b1-4a24-bee1-2b7a10ab5dd1)

![Screen Shot 2019-03-12 at 13.30.49.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/2673737d-12ab-48b7-b2d1-e293ac63b1ba)

Also, on the second list, do we need this many `Role Binding` titles?  
Maybe we could remove this one:

![Screen Shot 2019-03-12 at 13.35.00.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/3b074908-1baa-44f3-a5f2-857aa27a2b35)
?

**Comment by jesusreal** [comment] 2019-03-13 11:07
Probably a duplicate of #582. @dariadomagala can you confirm?

**Comment by jesusreal** [comment] 2019-03-15 10:05
Fixed by #582. Further consistency will be applied on a follow up task.

**Closed** 2019-03-15 10:05 UTC
Labels: area/console, bug, question
