### ISSUE TITLE
Edit namespace labels and memory config in modal

### ISSUE THREAD

**Issue by sjanota** [kyma-project/console#1234] opened 2019-09-09 12:48 UTC
**Description**

- User can edit labels
- User can edit memory configurations
- Include istio sidecar configuration

**AC**

- Modal is dismissed on <ESC>
- New labels are validated and added on <tab> button
- label field is auto-focussed when modal is opened 
- avoid unnecessary mutations, ( detect dirty state - i.e :only labels modified)

**Attachments**

https://app.zeplin.io/project/5ab0db46508f1e7a678a01c1/screen/5d148b753ea6b873570ca62f

![Screen Shot 2019-09-09 at 15.53.06.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/2d1d43f3-b3cd-4e9f-b07d-7e36c25ab5b6)
![Screen Shot 2019-09-09 at 15.49.46.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/ea8c2b26-1fe0-497e-9df7-efc5b8542e64)

**Comment by kwiatekus** [comment] 2019-10-07 13:26
Duplicate of #1233

**Comment by kwiatekus** [comment] 2020-07-15 11:10
Labels are edited inline in the page header.

**Closed** 2020-07-15 11:11 UTC
Labels: area/console, enhancement
