### ISSUE TITLE
Addons: editing labels is buggy

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1422] opened 2019-11-22 12:13 UTC
**Description**

When I open the _create addon modal_, there's an input field for labels.
It works well when I follow the happy path (enter a valid label separated by `=`) but when I don't (by entering a space or `,`), the field becomes unusable. I can't either change/remove my input or submit it.

Consider using shared `LabelInput` component.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment] 2020-05-07 10:26
@parostatkiem I cannot reproduce it.
Please verify. If you confirm, close it please

**Comment by parostatkiem** [comment] 2020-05-07 11:03
It looks like the "space" issue has been resolved but I can still enter some invalid labels, such as
![image](https://user-images.githubusercontent.com/22825433/81287426-064b9480-9063-11ea-9405-4085660082b4.png)

According to the internet,

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and 
alphanumerics between.

**Comment by kwiatekus** [comment] 2020-11-24 13:22
🍰  It was not causing much trouble so far. Closing as it has no priority

**Closed by kwiatekus** 2020-11-24 13:22 UTC
Labels: wontfix
